### ISSUE TITLE
Speed improvements?

### ISSUE THREAD

**Issue by kkirby** [mozilla/sweet.js#447]
Hi. I remember using SweetJS awhile back (a year to two years ago), and I remember SweetJS being panfully slow with complex macros. I'm wondering if any headway has been made in speed and optimizations?

**Comment by natefaubion** [comment]
Yes, we've made tons of speed improvements since then, so its significantly faster than it was, but as always, as you add more features you're constantly fighting performance. For example, the included `stxcase.js` macros have probably doubled in size, which adds to the warm up time. I think as we get modules we can start splitting stuff like that out (maybe into its own org?) so you only pay for what you really need.

I've noticed the es6-modules branch is slower for me than master, so we'll likely have many more opportunities to come :)

**Comment by natew** [comment]
Just want to chime in, while not being very helpful. I've got a simple setup where I'm running:

```
sjs -m es6-macros -r jsx-reader in.js
```

in.js contains just a simple react class and returns some JSX tags. I'm seeing linear increases in incremental compile time based on number of JSX tags.

I stepped through adding 10 tags and recompiling and it seems to add 20-40ms for every ten tags. Even with es6 disabled.

I'm sure this isn't an easy problem to tackle. But figured I'd throw in my +1 in this case. I'm new to this whole area but would love to help as well. Going to start browsing the repo and getting familiar.

**Comment by jlongster** [comment]
To follow-up on @natew's comment, I think the main culprit of that slowdown is jsx-reader and how we use macros. There might be a way we can transform jsx faster. sweet will slow down the more macros you use, but I don't think it should be that bad.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
