### ISSUE TITLE
Generate method within an ES6 class: unexpected semicolon

### ISSUE THREAD

**Issue by buunguyen** [mozilla/sweet.js#454]
Hello, I want to write a macro that generates a method inside the context of an ES6 class. For example:
```
class ApiDef {
  @post('users/login'): login
}
```
Should generate:

```
class ApiDef {
  login() { return ['post', 'users/login'] }
}
```

This is the macro I'm writing:

```
macro $post {
  rule { ($x): $y } => { $y() {return ['post', $x]} }
}
```

But `$post('/users/login'): login` generates this:
```
login();
{
    return [
        'post',
        '/users/login'
    ];
}
```
Notice that there's a semicolon between `login()` and `{`. How can I get rid of it?

Also a related question: is it possible to use the `@` prefix in place of `$` (i.e. so that the macro becomes `@post`? I tried that but received an error.

**Comment by disnet** [comment]
Looks like your macro works as intended: http://bit.ly/1MNINCb

You're seeing the extra `;` because outside of the context of a `class` declaration `$post` will expand to:

```js
login() { return [ 'post', '/users/login' ] }
```

and the parser and code generator will just do automatic semicolon insertion. In a `class` though it does the right thing since no `;` need to be inserted.

> Also a related question: is it possible to use the `@`` prefix in place of `$``

You can, it's a little non-intuitive though:

```js
macro (@post) {
  rule { ($x): $y } => { $y() {return ['post', $x]} }
}
class ApiDef {
  @post('users/login'): login
}
```

A `@` is always punctuator (like `*` or `;`) in sweet.js so it can't be part of an identifier normally. But sweet supports multi-token identifiers in macros by wrapping the macro name in parens so by doing `(@post)` we are creating a macro with out of the two identifiers `@` and `post`.

**Comment by buunguyen** [comment]
Great, everything works now. Thank you for your help!
