### ISSUE TITLE
Support ES7 async/await

### ISSUE THREAD

**Issue by buunguyen** [mozilla/sweet.js#456]
This is supported (with experimental flag) in both Traceur and Babel. I can't use sweet right now because it throws when seeing `async`, `await`.

**Comment by m1sta** [comment]
I'd like to see this resolved by somehow allowing *anything* as the output of a sweet.js macro.

**Comment by jpdery** [comment]
I'd really like to see that as well.

**Comment by disnet** [comment]
We rely on esprima as our parser and AFAIK async/await hasn't been implemented in the esprima harmony branch yet (https://github.com/jquery/esprima/issues/1079).

**Comment by m1sta** [comment]
So it's esprima and not escodegen that's the bottleneck?

**Comment by disnet** [comment]
Right, I think escodegen has support for async/await: https://github.com/estools/escodegen/issues/220.

**Comment by m1sta** [comment]
How difficult would it be to switch esprima for acorn-babel?

**Comment by disnet** [comment]
I haven't tried but I suspect it's nontrivial. You'd need to make acorn work over syntax objects rather than the raw source because the parser has to accept the result of expansion (so the parser can do `resolve` at the appropriate places).

Really the right solution is not acorn or esprima. Sweet is already building up an AST (a TermTree in sweet jargon) in `enforest` which we then destruct back to a flat array after expansion is finished only to build another AST with esprima. We just need to get `enforest` to produce a robust enough TermTree that is Parser API compatible.

**Comment by disnet** [comment]
I'm mass closing issues due to the release of 1.0 obviating lots of bugs. If you feel this issue is something we still need to address feel free to reopen.
