### ISSUE TITLE
Can't make a case macro using makeDelim

### ISSUE THREAD

**Issue by ThomasCrvsr** [mozilla/sweet.js#467]
To experiment a little, I try to write an infix macro (..) which is quite simple : 1 .. 3 expands to [1, 2, 3].

Here is the code : 
```
macro (..) {
    case infix { $low:lit | _ $high:lit } => {
            var low = unwrapSyntax(#{low});
            var high = unwrapSyntax(#{high});

            var arr = [];
            for (var i = low; i <= high; i++) {
                arr.push(i);
            }

            var arrStx = makeDelim('[]', arr, #{$low});
            return [arrStx]
    }
}
```

I've got an error : "ASSERT: expecting a syntax object". Does makeDelim() behave differently than makeValue() etc... ?

**Comment by natefaubion** [comment]
You have a few problems with your macro:
* You are unwrapping the literal tokes `low` and `high` which results in strings `"low"` and `"high"` because you are missing the leading `$` on the pattern variable.
* You are pushing numbers into `arr`, not syntax objects representing numeric literals (I think this is what is causing the error you are referring to).
* You aren't interspersing commas into your array so it's not valid JS (sweet.js doesn't do this automatically with `makeDelim`).

You need to use `makeValue`, and I'd just use `letstx` to load a repeater into the pattern env.

```js
macro (..) {
    case infix { $low:lit | _ $high:lit } => {
        var low = unwrapSyntax(#{ $low});
        var high = unwrapSyntax(#{ $high });
        var arr = [];
        for (var i = low; i <= high; i++) {
            arr.push(makeValue(i, #{ here }));
        }
        letstx $nums ... = arr;
        return #{ [ $nums (,) ... ] };
    }
}

var a = 1 .. 4;
```
```js
var a = [
    1,
    2,
    3,
    4
];
```

**Comment by ThomasCrvsr** [comment]
For the first point it was a mistake when I reported the code I had in this issue, I took care of unwrapping $low and $high ^^

Thanks, it works perfectly ! :)

Just by curiosity, is there a way to inline arrays in the generated code ?

**Comment by natefaubion** [comment]
> Just by curiosity, is there a way to inline arrays in the generated code ?

That lives in `escodegen`. You'd have to look at its options. You can pass `escodegen` options in calls to `sweet.compile` through the `escodegen` key.

**Comment by ThomasCrvsr** [comment]
Okay, I'll have a look. Thanks !
