### ISSUE TITLE
How to match ( in a pattern?

### ISSUE THREAD

**Issue by mehdishojaei** [mozilla/sweet.js#477]
I want to define ES2015 Spreads as an infix macro, something like:
```js
macro ... {
    case infix { $name ( | _ $arr:expr ) } => {
        return #{
            $name.apply(undefined, $arr)
        };
    }
}

var n = sum(...[1, 2, 3]);
```
```
SyntaxError: [syntaxCase] Infix macros require a `|` separator
2:     case infix { $name ( | _ $arr:expr ) } => {
                  ^
```
Is it possible through extending the `readtable` or something else?

**Comment by vendethiel** [comment]
you should be able to use `$[(]`

**Comment by mehdishojaei** [comment]
I tried that, but not works.
```
Error: Line 8: Unexpected end of input
[... ) } )  ...]
```

**Comment by vendethiel** [comment]
ah; I understand now. I don't think "infix" is the correct one today, though...

**Comment by disnet** [comment]
Spread is not currently possible since macros can't match outside of their enclosing paren/brace/bracket.

Rest can be implemented by making a `function` macro that just looks for `...` in the parameter list, but to implement spread what sweet.js needs is something like Racket's [implicit forms](http://docs.racket-lang.org/guide/module-languages.html#%28part._implicit-forms%29). Implicit forms would mean that a function call like `foo(...[1,2,3])` would implicitly be something like `#%app(foo, ...[1,2,3])` and then you could write a macro that appropriately transforms `#%app` forms.

**Comment by mehdishojaei** [comment]
@disnet Thanks for your grate work. Macros are grate and I think sweet.js can be more powerful. Do you have a plan for such improvements?

**Comment by disnet** [comment]
@mehdishojaei it's definitely on the roadmap! No promises on a timeline though :)

**Comment by mehdishojaei** [comment]
@disnet Thanks.
