### ISSUE TITLE
Extendable syntaxes

### ISSUE THREAD

**Issue by bopjesvla** [mozilla/sweet.js#529]
Extendable syntaxes would allow for:

- the usage of independently written macros with the same name, provided that they're used in different contexts
- the inline extension of an imported macro without forking a module
- anything that requires backtracking, such as the `macro` syntax

The most natural implementation I can think of would be to allow syntax functions to return null, after which the reader tracks back and tries the previous macro with the same name:

```
syntax each = ctx => {
	let variable = ctx.next("expr").value,
		OF = ctx.next().value,
		iterable = ctx.next("expr").value,
		body = ctx.next().value
	
	if (variable && iterable && OF.isIdentifier("of") && body.isBraces()) {
		return #`for (${variable} ${OF} ${iterable}) ${body}`
	}
	
}
syntax each = ctx => {
	let iterable = ctx.next("expr").value,
		body = ctx.next().value
	
	if (iterable && body.isBraces()) {
		return #`for ($_ of ${iterable}) ${body}` // yeah this wouldn't work because of hygiene
	}
}

each x of y {
	x()
}

each y {
	$_()
}
```

This would cover a lot of the same ground as readtables.

**Comment by elibarzilay** [comment]
I'm not sure that I follow this completely, but it sounds fishy.  Specifically: "provided that they're used in different contexts" --- one major aspect of macros is that they are *local* transformations.

Also, I get the impression that this is kind of like allowing a function to return an "unknown" value, which could be handled by other definitions of the same function, so that one of them can return an answer.  But if this is true, then this smells like something that can suffer from an order-of-evaluation thing, and should anyway be addressed by proper code as you'd do in the case of functions.

Finally, I suspect that I'm missing something because of the last comment, since I don't see how this is related to readtables.

**Comment by bopjesvla** [comment]
> I'm not sure that I follow this completely, but it sounds fishy. Specifically: "provided that they're used in different contexts" --- one major aspect of macros is that they are local transformations.

Yeah, that was sloppy wording. My use of "context" was colloquial there.  I meant "the usage of independently written macros with the same name in the same scope, provided they are used in different situations."

> Also, I get the impression that this is kind of like allowing a function to return an "unknown" value, which could be handled by other definitions of the same function, so that one of them can return an answer.

That's correct!

> But if this is true, then this smells like something that can suffer from an order-of-evaluation thing,

Newest-first evaluation makes perfect sense in a tower of languages where writers of new macros are aware of the way older macros work. But yeah, if you include two macros with the same name with the intention of using them side-by-side, you should obviously be mindful of the order.

> and should anyway be addressed by proper code as you'd do in the case of functions.

You completely lost me here.

> Finally, I suspect that I'm missing something because of the last comment, since I don't see how this is related to readtables.

I merely meant that this would make syntaxes more like the expand-phase equivalent of the readtable implementation in 0.7.

-----

An example of a simple 0.7-style macro for which I can't see a simple 1.0 counterpart without backtracking:

```
macro ex {
	rule { $i:ident + 5 } => { $i * 123 }
	rule { $e:expr } => { $e * 456 }
}

ex x + 5 + 3;     // x * 123 + 3
ex y * 3 + 7;     // (y * 3 + 7) * 456
```

The problem here is that once you read something as an identifier, you can't read it as an expression.

**Comment by disnet** [comment]
I think what you actually want in this proposal is just a way to rewind the macro context iterator:

	syntax m = function (ctx) {
		if (ctx.next().value.isIdentifier()) {
			// ...
		} else {
			ctx.reset();
			let expr = ctx.next('expr');
			// ...
		}

I’m not sure that `.reset` is the right name but something like that.

**Comment by vendethiel** [comment]
I'm not sure that currently exists, so maybe a non-advancing version of `next` i.e. `peek`?

**Comment by bopjesvla** [comment]
`ctx.reset` would cover only one use case. Extendable syntaxes would make sweetening a language constructed with sweet.js as easy as sweetening plain JS, without having to worry about whether a keyword/punctuator is taken or not. It also allows cherrypicking certain behaviours for a macro. I'll write up an example in one or two hours.

**Comment by disnet** [comment]
Your previous example could also be written with the later definition of `each` dispatching to the earlier definition of `each` if the later one fails to match its pattern. Something like:

```js
syntax each = ctx => {
    let iterable = ctx.next("expr").value,
        body = ctx.next().value

    if (iterable && body.isBraces()) {
        return #`for ($_ of ${iterable}) ${body}` // yeah this wouldn't work because of hygiene
    }
}
syntax each = ctx => {
    let variable = ctx.next("expr").value,
        OF = ctx.next().value,
        iterable = ctx.next("expr").value,
        body = ctx.next().value

    if (variable && iterable && OF.isIdentifier("of") && body.isBraces()) {
        return #`for (${variable} ${OF} ${iterable}) ${body}`
    }
   return #`each`;
}
```

This makes it clear what is going on and doesn't rely on fragile ordering semantics.

**Comment by elibarzilay** [comment]
@bopjesvla:

> > and should anyway be addressed by proper code as you'd do in the case of functions.

> You completely lost me here.

That was actually the main point I had, but phrased in a stupid way.  What I meant is that if you have a case where you want to specify some functionality via code that is defined in multiple places, then you have a bunch of tools to do so.  One obvious example of this is objects; another would be this kind of a distributed matcher thing (which is actually similar to a kind of a hook variable).  Now, my point is that you *have* a proper language for macros, so there's no need to complicate the macro system in order to accomodate things like that -- you just write code and deal with it in any of the "usual ways" you'd deal with it where "usual ways" means in plain runtime-level JS code.

(And I don't know what you mean by "expand-phase equivalent of the readtable implementation", but it's clear (to me, at least) that it's unrelated...)

----

As for the motivating example that you posted, of using a macro with `rule`s: I'm kind of surprised that there's not much complainage about the lack of `rule`-based macros (and I'm assuming that they're not there yet).  However, if they really *are not* implemented yet, then that makes me happy, even when it will make macros harder to write.

And this is a point that needs some explicit explaining...

The thing is that Scheme, in the "standard" sense (whatever little that means), has got that part (the `syntax-rules`) in a way that can, in many ways, be described as "wrong".  Macros based on `syntax-rules` suffer from a bunch of problems with no good solution --- and most of these problem come from the basic fact that there is no meta-level code running, just simple pattern-template-based rewrite rules.  The result of this wrong-ness can be seen in the fact that `syntax-rules` based macros in Racket are almost never used for *public* functionality (they are used for internal stuff though).

So when it comes to writing these kinds of macros, I completely agree that something that is rule-based is going to be extremely convenient to have --- but that should come after there's some actual experience writing macros without it, and looking for something that is useful, convenient, and doesn't suffer from the simple-rewrite-rule problems.  (And something like Racket's `syntax-parse` is probably a good idea, especially for an infixish language, and IIUC, those `rule`s in the past were pretty close to `syntax-parse`.)

**Comment by bopjesvla** [comment]
@disnet Explicit propagation would be great! In your example, I assume `return #'each';` is supposed to be preceded by `ctx.reset();`. If not, the second macro would still gobble up everything before the first one gets a shot. Also, if that's the way we go about it, there should be a way to programmatically retrieve a macro's name as a syntax object, like `ctx.name()`. 

> This makes it clear what is going on and doesn't rely on fragile ordering semantics.

I'm not sure I understand what you mean by ordering semantics, but if we go by the above, `ctx.reset(); return ctx.name();` would do exactly the same as what I proposed `return null` would do, right? Feel free to tell me if I'm way off base here.

The only gripe I have with the proposal is that reader macros (i.e. macros that handle `ctx.next()` and matching inside syntax declarations) would benefit greatly from being able to skip to the next definition without being aware of the top-level macro context, which would be necessary for `ctx.reset()`, and `ctx.name()`, but not for `return null`.

A potential practical issue is that it suddenly becomes very important that declarations like `syntax (:) = ctx => #':'` have absolutely no side effects, which might be difficult for some punctuators and keywords. This issue of self-replacement doesn't exist in my original proposal.

**Comment by bopjesvla** [comment]
@elibarzilay If I understand you correctly, you think extendable macros should be implemented using the current macro system, right? As far as I know, there's no way to retrieve or fall back on the previous definition of a syntax in the same scope.

> What I meant is that if you have a case where you want to specify some functionality via code that is defined in multiple places, then you have a bunch of tools to do so. One obvious example of this is objects;

Wait, are you suggesting that extendable syntaxes should be implemented using some kind of additional scoping system? I doubt that'd be very performant.

**Comment by elibarzilay** [comment]
@bopjesvla, no additional scoping system.  In fact, I'm religiously sticking to the opposite side of that: no additional anything, just plain code.  A result of that is: in plain JS code you don't have some built-in way to define a function in several disconnected places --- if you want that, you need to implement it yourself (as in the hook example) --- and I'm saying that the same should hold for macro code.

This is separate from the issue of being able to rewind the macro context.  There should be a way to do that, especially given that in JS some of the syntactic categories overlap (ie, identifiers and expressions).

*But*, this way should not be via some multiple definitions of the same macro that the expander tries one by one.  Why not?

1. It's fragile: if each definition is defined in a different file, then loading files in a different order leads to a different macro.

2. It doesn't let me write a deterministic macro --- one that always expands in the same way, determined completely by the code I have written.  It doesn't let me do that since you can add some definition of the same name that will mess up with my definition.

3. The last point is even more problematic in case of a recursive macro: now not only can clients of my macro get different behavior --- my own recursive macro uses can be messed up.

And the thing is that all of this holds for any function, not just macros.  So, if for your own case you have a use for defining a single function in multiple places then you use one of these tools (a class, a hook variable, etc), but that's an explicit decision that you made for your own use rather than make all functions overrideable.

**Comment by bopjesvla** [comment]
Ah, now I almost see where you're coming from. Two more things: does "the hook example" refer to disnet's proposed implementation? Do you agree something like that should be possible? (Also, is everyone aware of the fact that it's currently impossible? Because that's why I started this issue.)

**Comment by elibarzilay** [comment]
By the hook example, what I mean is that you come up with some machinery to do such dynamic extensions.  For example

    let make_hooked = def => {
        let hooks = [];
        let fun = x => {
            for (let h of hooks) {
                let r = h(x);
                if (r !== undefined) return r;
            }
            return def;
        }
        fun.add = h => hooks.push(h);
        return fun;
    };

    let add1 = make_hooked("I don't know");
    add1.add(x => { if (typeof x === "number") return x+1; });
    add1.add(x => { if (typeof x === "string") return x+" one"; });

But what I *don't* want is for *all* functions to be dynamically modifiable like this.  There are times when this is desirable, but the default should not have it.

As for agreeing that something like that should be possible: it sounds to me like it should, but that's mostly unrelated to what you said (I wouldn't reply if it wasn't for the readtable mention which was very confusing).

**Comment by disnet** [comment]
> I'm kind of surprised that there's not much complainage about the lack of rule-based macros (and I'm assuming that they're not there yet)

Right, issue #515 is about their reintroduction. Definitely post-modules and we should be careful about it. Modeling them more after `syntax-parse` is 💯.

> I assume return `#'each';` is supposed to be preceded by `ctx.reset();`

Yes indeed.

> Also, if that's the way we go about it, there should be a way to programmatically retrieve a macro's name as a syntax object, like `ctx.name()`

Definitely, that was in my mind but didn’t make it into code for the MVP. Trivial to add but not critical until we have syntax creation functions and the need to perform hygiene shenanigans.

In this case though, you don’t want `ctx.name()` since that would just make it a recursive definition. You want the previous binding via `#'each'`.

> I'm not sure I understand what you mean by ordering semantics…

Yes they do the same but explicit rather than implicit (you may have noticed explicit vs implicit is my bugaboo 😄).

> Also, is everyone aware of the fact that it's currently impossible?

Yes, something like `.reset()` was in my head (not in code 😄) to handle cases like this.

**Comment by bopjesvla** [comment]
I meant that declaring multiple definitions in a single scope is not yet possible.

```
syntax test = ctx => #`THISWORKS`
syntax test = ctx => #`test`

test
```

outputs `test`, not `THISWORKS`.

> As for agreeing that something like that should be possible: it sounds to me like it should, but that's mostly unrelated to what you said (I wouldn't reply if it wasn't for the readtable mention which was very confusing).

It seems like you were mostly put off by the way I presented the issue. The only difference between disnet's implementation and mine is that in my implementation the null return value implies what disnet made explicit. The three points you mentioned all equally apply to disnet's proposal.

**Comment by elibarzilay** [comment]
Maybe I'm confused, but there is a huge difference between the two: in what you want to write there is a single `test` macro that is defined in several places, instead of a single definition that does it all.  I think that such magical thing of "we're assembling a function from bits that are here and there" is generally dangerous, and it's much better to keep it to just plain functions.  In other words, I expect what you wrote to either fail because there are duplicate definitions of the same macro, or to produce `test` because the second macro overwrites the first.

**Comment by disnet** [comment]
Right, that example actually reveals a bug. Apparently, duplicate `syntax` declarations in the same scope have "last-defined wins" semantics like `var` (aka hoisting) but they really should be an early error like `let`/`const`.

To actually override a `syntax` you would need to be in different scopes. Either via functions:

```js
syntax test = ctx => #`outer`;
function foo() {
  syntax test = ctx => #`test`;
}
```

or imports:

```js
import { test } from "test";
syntax test => #`test`;
```

**Comment by elibarzilay** [comment]
TBH, I initially suspected that it might be that each `syntax test` has its own definition that applies for the rest of the scope, rather than changing the existing definition.  That is, something like a `let` in ML or a `define*` in Racket.  But then I tried this:

    syntax test  = ctx => { return #`foo`; }
    syntax test1 = ctx => { return #`test`; }
    syntax test  = ctx => { return #`bar`; }
    test1;

and the result of `bar` shows that this is changing the function instead of redefining it.

BTW#1, looks like `syntax` always expects something that looks like a function?  Even a form that evaluates to a function but doesn't look like one gives me a `Cannot read property 'map' of undefined`.

BTW#2, besides the obvious(-to-racketeers) uses of this it's also a way to get to do stuff at the syntax toplevel.  For example,

    syntax _dummy = (test = ctx => #`something_else`);

which of course doesn't work at all now.

**Comment by disnet** [comment]
>  looks like syntax always expects something that looks like a function?

Yeah, unintentional limitation at the moment.

**Comment by bopjesvla** [comment]
> Maybe I'm confused, but there is a huge difference between the two: in what you want to write there is a single test macro that is defined in several places, instead of a single definition that does it all. I think that such magical thing of "we're assembling a function from bits that are here and there" is generally dangerous, and it's much better to keep it to just plain functions.

disnet's `each` definition is also assembled of multiple pieces. `ctx.reset(); return #'each'` and `return null` do the same thing.

> Right, that example actually reveals a bug. Apparently, duplicate syntax declarations in the same scope have "last-defined wins" semantics like var (aka hoisting) but they really should be an early error like let/const.

But you proposed a duplicate `each` definition earlier?

I'm probably shooting myself in the foot here, but the distinction you're making between imported and inline declarations is counterintuitive. Since `import` inserts `test` in the current scope, I expect these to have the same result:

```
syntax test = ctx => #`THISWORKS`
syntax test = ctx => #`test`
```

```
import { test } from "test"; // export syntax test = ctx => #`THISWORKS`
syntax test = a => #`test`;
```

**Comment by elibarzilay** [comment]
> disnet's each definition is also assembled of multiple pieces.

I assumed it was pseudo code which you would resolve by using different names.  Again, a normal function definition is all contained between a "{" and a "}" (or an expression that evaluates to a function) --- macros *should not* be different.

**Comment by disnet** [comment]
> But you proposed a duplicate each definition earlier?

Just a pseudo code example in which I momentarily forgot about correct scoping :)

As @elibarzilay mentioned there are other binding forms like Racket's `define*` we could take inspiration from to handle different scoping rules. We could either modify `syntax` to take on scoping rules that are "better" (ie. redefine in the current scope) or have `syntax` take on `let`/`const` scoping (ie. redeclaration is an error) and introduce additional binding forms to handle additional scoping rules.

The key point is that your use-cases can be handled with the appropriate application of already existing (or soon to be existing) macro features without changing the fundamental idea that macros are just (compile time) functions operating on syntax.

**Comment by bopjesvla** [comment]
If we go by redefining, would you be opposed to exposing the old syntax transformer to the new definition? So you could do:

```
syntax test = ctx => {
	let {value} = ctx.next()
	return #`typeof ${value}`
}

test 5 // typeof 5

syntax test = ctx => {
	let {value} = ctx.next()
	return value.isIdentifier() ? #`${value}.type` : ctx.previousSyntax()
}

syntax test = ctx => {
	let {value} = ctx.next()
	return value.isNumber() ? #`2 + ${value}` : ctx.previousSyntax()
}

test 5 // 2 + 5
test hello // hello.type
```

This would allow for same-scope propagation without requiring additional bindings. I'm not sure it makes sense that `previousSyntax` is a method on the macro context, though. Maybe sandbox it?

**Comment by bopjesvla** [comment]
I forgot to reset the contexts before passing them, but you get the point.

**Comment by elibarzilay** [comment]
@bopjesvla:

1. The `define*` that disnet is talking about is *not* redefining things, it's a new definition, which has the rest of the code in its scope.  It's a bit tricky for people who don't come from some heavy functional background, but what it gives you, in JS terms, is the ability to do this:

        var x = 1;
        var x = x + 2;
        var x = () => x;
        // and now x() returns 3

    The way to think about it is as if each `x` gets automatically renamed:

        var x0 = 1;
        var x1 = x0 + 2;
        var x2 = () => x0;
        // and now x() returns 3

2. It's also tricky since it doesn't allow recursive definitions.  The way that ML solves it is by having a separate construct for recursive definitions.  It gets even more complicated: that recursive construct needs to be able to deal with multiple definitions in case of mutual recursion.  In short: it can get very inconvenient.

3. The bottom line is that this would be extremely confusing for JS people, to say the least.  And this means that it would be pretty bad to make it work for `syntax` definitions since they won't be following the usual rules for plain definitions.

4. Of course, one of the things that you should eventually be able to do is write some macros that do this, and then play with your own language and see how you like it...

5. Still, you seem to be blocked on having some way to define a macro in multiple separate chunks --- that is the basic thing that I said is a mistake, since it's ***really*** best to avoid more confusion in an area that is already confusing, and have the rules for `syntax` definitions be the same as the ones for `function`.

6. If you really don't see the point in what I'm saying, then it should be easy to implement it yourself --- just like I did with the hooks example.  Something like putting that code at the syntax level, and then, assuming some `for_syntax` thing that evaluates code at the syntax level, something like this:

        syntax test = make_hooked();
        for_syntax test.add(ctx => ... your first definition ...);
        for_syntax test.add(ctx => ... your second definition ...);
        for_syntax test.add(ctx => ... your third definition ...);

    (and yes, you still need a way to reset the input.)

7. I'll drop it now.

**Comment by bopjesvla** [comment]
I'm sorry if I gave you the impression I didn't hear what you were saying. You successfully convinced me that extendable syntaxes are a bad idea, and that a `define*`-like mechanic is superior, if difficult. And don't get me wrong, I don't doubt that your hook example works.

The point of this issue was to ask for the introduction a simple mechanic that allows multiple `syntax` definitions to work together. I used the phrase "extendable macros" because that seemed synonymous to me at the time, as I hadn't considered that true extension of a syntax would affect previously declared macros.

This had fully dawned on me by the time I wrote my previous comment, in which I suggested to allow _some_ `define*`-like behaviour in syntax declarations. Not by overwriting recursive behaviour like `define*`, but by exposing what you call "the rest of the code" through a function with a fixed name, in the same way syntaxTemplate is exposed.

In JS terms, it would allow you to do this:

```
var fib = n => n
var fib = n => n < 2 ? previousVar(n) : fib(n - 1) + fib(n - 2);
var fib = n => n % 2 == -1 ? previousVar(-n) : previousVar(n)
var fib = n => Object.is(n % 2, -0) ? -previousVar(-n) : previousVar(n)

// now fib(-8) returns -21
```

This doesn't infer with the normal use of functions at all. Only when `previousVar` is involved, things become abnormal. Recursion is dead simple.

Another reason why I'd prefer one binding form with multiple uses is that you don't have to write binding-form-specific reading macros. You could define a `read-or-pass-on` macro in such a way that

```
import read from "read-or-pass-on" for macros

syntax test = ctx => {
	read ctx { a:identifier b:punctuator }
	return #`${a} ${b} ${a}`
}
syntax test = ctx => {
	read ctx { a:identifier b:identifier }
	return #`${a} + ${b}`
}
```

expands to

```
syntax test = ctx => {
	let a = ctx.next().value;
	if (!a || !a.isIdentifier()) {
		ctx.reset()
		previousSyntax(ctx)
	}
	let b = ctx.next().value;
	if (!b || !b.isPunctuator()) {
		ctx.reset()
		previousSyntax(ctx)
	}
	return #`${a} ${b} ${a}`
}
syntax test = ctx => {
	if (!a || !a.isIdentifier()) {
		ctx.reset()
		previousSyntax(ctx)
	}
	let b = ctx.next().value;
	if (!b || !b.isIdentifier()) {
		ctx.reset()
		previousSyntax(ctx)
	}
	return #`${a} + ${b}`
}
```

If this is terribly misguided, please tell me. Don't feel obliged to explain why, though, since you've put in more than enough effort into this. I'll close this after a few days of inactivity.

**Comment by disnet** [comment]
I'll close now since I don't think this issue represents a thing we want to work on right now. My suspicion is that once we've gone down the Racket path for a while your use-cases will be satisfied.

If not we can reopen the discussion then :)

**Comment by bopjesvla** [comment]
That's fair. I c/p'ed the relevant discussion to https://groups.google.com/forum/#!topic/sweetjs/F3kV24FagR8 if anyone is interested in explaining why the Racket path is better.
